# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\00工作\01上课\02Robot\04Python与上位机开发\01课前资料\02代码\Py上位机示例代码\项目实战02-串口调试助手\v3_弹出对话框\ui\serial_setting_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(354, 216)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.Label_2 = QtWidgets.QLabel(self.groupBox)
        self.Label_2.setObjectName("Label_2")
        self.gridLayout.addWidget(self.Label_2, 0, 0, 1, 1)
        self.cb_bt = QtWidgets.QComboBox(self.groupBox)
        self.cb_bt.setObjectName("cb_bt")
        self.cb_bt.addItem("")
        self.cb_bt.addItem("")
        self.cb_bt.addItem("")
        self.gridLayout.addWidget(self.cb_bt, 0, 1, 1, 1)
        self.Label = QtWidgets.QLabel(self.groupBox)
        self.Label.setObjectName("Label")
        self.gridLayout.addWidget(self.Label, 1, 0, 1, 1)
        self.cb_data = QtWidgets.QComboBox(self.groupBox)
        self.cb_data.setObjectName("cb_data")
        self.cb_data.addItem("")
        self.cb_data.addItem("")
        self.cb_data.addItem("")
        self.gridLayout.addWidget(self.cb_data, 1, 1, 1, 1)
        self.Label_4 = QtWidgets.QLabel(self.groupBox)
        self.Label_4.setObjectName("Label_4")
        self.gridLayout.addWidget(self.Label_4, 2, 0, 1, 1)
        self.cb_stop = QtWidgets.QComboBox(self.groupBox)
        self.cb_stop.setObjectName("cb_stop")
        self.gridLayout.addWidget(self.cb_stop, 2, 1, 1, 1)
        self.Label_5 = QtWidgets.QLabel(self.groupBox)
        self.Label_5.setObjectName("Label_5")
        self.gridLayout.addWidget(self.Label_5, 3, 0, 1, 1)
        self.cb_check = QtWidgets.QComboBox(self.groupBox)
        self.cb_check.setObjectName("cb_check")
        self.gridLayout.addWidget(self.cb_check, 3, 1, 1, 1)
        self.Label_6 = QtWidgets.QLabel(self.groupBox)
        self.Label_6.setObjectName("Label_6")
        self.gridLayout.addWidget(self.Label_6, 4, 0, 1, 1)
        self.cb_stream = QtWidgets.QComboBox(self.groupBox)
        self.cb_stream.setObjectName("cb_stream")
        self.gridLayout.addWidget(self.cb_stream, 4, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 4)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(122, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnOk = QtWidgets.QPushButton(Dialog)
        self.btnOk.setObjectName("btnOk")
        self.horizontalLayout.addWidget(self.btnOk)
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.cb_bt.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "串口设置对话框"))
        self.groupBox.setTitle(_translate("Dialog", "设置串口"))
        self.Label_2.setText(_translate("Dialog", "波特率："))
        self.cb_bt.setItemText(0, _translate("Dialog", "9600"))
        self.cb_bt.setItemText(1, _translate("Dialog", "115200"))
        self.cb_bt.setItemText(2, _translate("Dialog", "256000"))
        self.Label.setText(_translate("Dialog", "数据位："))
        self.cb_data.setItemText(0, _translate("Dialog", "1位"))
        self.cb_data.setItemText(1, _translate("Dialog", "1.5位"))
        self.cb_data.setItemText(2, _translate("Dialog", "2位"))
        self.Label_4.setText(_translate("Dialog", "停止位："))
        self.Label_5.setText(_translate("Dialog", "校验位："))
        self.Label_6.setText(_translate("Dialog", "流控制："))
        self.btnOk.setText(_translate("Dialog", "OK"))
        self.btnCancel.setText(_translate("Dialog", "Cancel"))
