# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\00工作\01上课\02Robot\04Python与上位机开发\01课前资料\02代码\Py上位机示例代码\07-PyQt5\自定义信号\ui\main_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(354, 139)
        self.gridLayout = QtWidgets.QGridLayout(MainWidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(104, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(MainWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(103, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.btnShow = QtWidgets.QPushButton(MainWidget)
        self.btnShow.setObjectName("btnShow")
        self.gridLayout.addWidget(self.btnShow, 1, 0, 1, 1)
        self.btnClose = QtWidgets.QPushButton(MainWidget)
        self.btnClose.setObjectName("btnClose")
        self.gridLayout.addWidget(self.btnClose, 1, 2, 1, 1)

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "主窗口"))
        self.label.setText(_translate("MainWidget", "主窗口"))
        self.btnShow.setText(_translate("MainWidget", "显示子窗口"))
        self.btnClose.setText(_translate("MainWidget", "关闭子窗口"))
