# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\00工作\01上课\02Robot\04Python与上位机开发\01课前资料\02代码\Py上位机示例代码\07-PyQt5\自定义信号\ui\sub_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SubWidget(object):
    def setupUi(self, SubWidget):
        SubWidget.setObjectName("SubWidget")
        SubWidget.resize(354, 134)
        self.gridLayout = QtWidgets.QGridLayout(SubWidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(104, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(SubWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(103, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.btn1 = QtWidgets.QPushButton(SubWidget)
        self.btn1.setObjectName("btn1")
        self.gridLayout.addWidget(self.btn1, 1, 0, 1, 1)
        self.btn2 = QtWidgets.QPushButton(SubWidget)
        self.btn2.setObjectName("btn2")
        self.gridLayout.addWidget(self.btn2, 1, 2, 1, 1)

        self.retranslateUi(SubWidget)
        QtCore.QMetaObject.connectSlotsByName(SubWidget)

    def retranslateUi(self, SubWidget):
        _translate = QtCore.QCoreApplication.translate
        SubWidget.setWindowTitle(_translate("SubWidget", "子窗口"))
        self.label.setText(_translate("SubWidget", "子窗口"))
        self.btn1.setText(_translate("SubWidget", "给主窗口发信息1"))
        self.btn2.setText(_translate("SubWidget", "给主窗口发信号2"))
