from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(668, 538)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./img/chess.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWidget.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.up = QtWidgets.QWidget(MainWidget)
        self.up.setObjectName("up")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.up)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(263, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lcdTimer = QtWidgets.QLCDNumber(self.up)
        self.lcdTimer.setAutoFillBackground(False)
        self.lcdTimer.setDigitCount(3)
        self.lcdTimer.setProperty("intValue", 10)
        self.lcdTimer.setObjectName("lcdTimer")
        self.horizontalLayout_2.addWidget(self.lcdTimer)
        spacerItem1 = QtWidgets.QSpacerItem(263, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 5)
        self.verticalLayout.addWidget(self.up)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left = QtWidgets.QWidget(MainWidget)
        self.left.setObjectName("left")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lcdBlack = QtWidgets.QLCDNumber(self.left)
        self.lcdBlack.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.lcdBlack.setDigitCount(3)
        self.lcdBlack.setProperty("intValue", 2)
        self.lcdBlack.setObjectName("lcdBlack")
        self.verticalLayout_2.addWidget(self.lcdBlack)
        self.widget = QtWidgets.QWidget(self.left)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelBlack = QtWidgets.QLabel(self.widget)
        self.labelBlack.setText("")
        self.labelBlack.setPixmap(QtGui.QPixmap("./img/black.png"))
        self.labelBlack.setScaledContents(True)
        self.labelBlack.setObjectName("labelBlack")
        self.verticalLayout_3.addWidget(self.labelBlack)
        self.verticalLayout_2.addWidget(self.widget)
        spacerItem2 = QtWidgets.QSpacerItem(20, 152, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 2)
        self.horizontalLayout.addWidget(self.left)
        self.chessboard = QtWidgets.QWidget(MainWidget)
        self.chessboard.setObjectName("chessboard")
        self.horizontalLayout.addWidget(self.chessboard)
        self.right = QtWidgets.QWidget(MainWidget)
        self.right.setObjectName("right")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.right)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lcdWhite = QtWidgets.QLCDNumber(self.right)
        self.lcdWhite.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lcdWhite.setDigitCount(3)
        self.lcdWhite.setProperty("intValue", 2)
        self.lcdWhite.setObjectName("lcdWhite")
        self.verticalLayout_4.addWidget(self.lcdWhite)
        self.widget_2 = QtWidgets.QWidget(self.right)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelWhite = QtWidgets.QLabel(self.widget_2)
        self.labelWhite.setText("")
        self.labelWhite.setPixmap(QtGui.QPixmap("./img/white.png"))
        self.labelWhite.setScaledContents(True)
        self.labelWhite.setObjectName("labelWhite")
        self.verticalLayout_5.addWidget(self.labelWhite)
        self.verticalLayout_4.addWidget(self.widget_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 152, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(2, 2)
        self.horizontalLayout.addWidget(self.right)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 8)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.down = QtWidgets.QWidget(MainWidget)
        self.down.setObjectName("down")
        self.verticalLayout.addWidget(self.down)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 8)
        self.verticalLayout.setStretch(2, 2)

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "黑白棋"))
